Repository kubernetes-sigs/testgrid, pull requests merged in 2024-11, with the labels that each got.

#17 Enable monthly dependency updates for UI.
  .github/dependabot.yml
Labels: lgtm, size/S, approved, cncf-cla: yes

#20 Dependabot: switch to a weekly cadence
  .github/dependabot.yml
Labels: lgtm, approved, size/XS, cncf-cla: yes

#19 Fix linting issues
  web/src/tab-summary.ts
  web/src/testgrid-app.ts
  web/src/testgrid-dashboard-summary.ts
  web/src/testgrid-data-content.ts
  web/src/testgrid-failures-summary.ts
  web/src/testgrid-grid-cell.ts
  web/src/testgrid-grid.ts
  web/src/testgrid-group-summary.ts
  web/src/testgrid-healthiness-summary.ts
  web/src/testgrid-index.ts
  web/src/testgrid-router.ts
  web/src/utils/navigation.ts
  web/stories/tab-summary.stories.ts
  web/stories/testgrid-grid-cell.stories.ts
  web/stories/testgrid-grid-column-header.stories.ts
  web/stories/testgrid-grid-row-name.stories.ts
  web/stories/testgrid-grid.stories.ts
  web/stories/testgrid-group-summary.stories.ts
  web/test/testgrid-data-content.test.ts
  web/test/testgrid-grid-cell.test.ts
  web/test/testgrid-grid.test.ts
  web/test/testgrid-index.test.ts
Labels: lgtm, approved, size/XL, cncf-cla: yes
