Repository kubernetes-sigs/testgrid, pull requests merged in 2025-08, with the labels that each got.

#35 fix(index): prevent shifting on dashboard group hover
  web/src/testgrid-index.ts
Labels: lgtm, approved, size/XS, cncf-cla: yes

#36 fix: add missing headers and extensions
  web/src/fake-api/data.json
  web/src/tab-summary.ts
  web/src/testgrid-app.ts
  web/src/testgrid-context.ts
  web/src/testgrid-data-content.ts
  web/src/testgrid-failures-summary.ts
  web/src/testgrid-grid-cell.ts
  web/src/testgrid-grid-header-row.ts
  web/src/testgrid-grid-headers-block.ts
  web/src/testgrid-grid-row.ts
  web/src/testgrid-grid.ts
  web/src/testgrid-group-summary.ts
  web/src/testgrid-healthiness-summary.ts
  web/src/testgrid-router.ts
  web/stories/tab-summary.stories.ts
  web/stories/testgrid-grid-cell.stories.ts
  web/stories/testgrid-grid-column-header.stories.ts
  web/stories/testgrid-grid-row-name.stories.ts
  web/stories/testgrid-grid.stories.ts
  web/stories/testgrid-group-summary.stories.ts
  web/test/testgrid-data-content.test.ts
  web/test/testgrid-grid-cell.test.ts
  web/test/testgrid-grid-column-header.test.ts
  web/test/testgrid-grid-header-row.test.ts
  web/test/testgrid-grid-headers-block.test.ts
  web/test/testgrid-grid-row-name.test.ts
  web/test/testgrid-grid-row.test.ts
  web/test/testgrid-grid.test.ts
  web/test/utils/link-template.test.ts
Labels: lgtm, size/L, approved, cncf-cla: yes

#46 add github issue template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/cleanup.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/question.md
Labels: lgtm, approved, ok-to-test, cncf-cla: yes, size/M

#53 feat(api): utilize Lit ReactiveControllers
  web/src/APIClient.ts
  web/src/controllers/api-controller.ts
Labels: lgtm, size/L, approved, cncf-cla: yes

#55 Remove alvaroaleman from owners
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS, cncf-cla: yes

#58 Remove cjwagner from OWNERS_ALIASES
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS, cncf-cla: yes

#60 fix(deps,lint): various dep and lint updates
  web/custom-elements.json
  web/package.json
  web/pnpm-lock.yaml
  web/src/controllers/api-controller.ts
  web/src/testgrid-app.ts
  web/src/testgrid-dashboard-summary.ts
  web/src/testgrid-data-content.ts
  web/src/testgrid-grid.ts
  web/src/testgrid-group-summary.ts
Labels: size/XXL, lgtm, approved, cncf-cla: yes

#61 migrate to the released material/web
  web/custom-elements.json
  web/package.json
  web/pnpm-lock.yaml
  web/src/testgrid-data-content.ts
  web/src/testgrid-index.ts
  web/test/testgrid-data-content.test.ts
  web/test/testgrid-index.test.ts
Labels: size/XXL, lgtm, approved, ok-to-test, cncf-cla: yes

#66 feat: add mutli-arch Dockerfile
  web/Dockerfile
  web/README.md
  web/docker-compose.yml
  web/package.json
  web/rollup.config.js
Labels: lgtm, approved, ok-to-test, cncf-cla: yes, size/M

#67 begin unifying styles
  web/WORKSPACE
  web/package.json
  web/src/styles/shared-styles.ts
  web/src/testgrid-grid-cell.ts
  web/src/testgrid-grid-column-header.ts
  web/src/testgrid-grid-header-row.ts
  web/src/testgrid-grid-row-name.ts
  web/src/testgrid-grid-row.ts
  web/src/testgrid-group-summary.ts
  web/src/testgrid-index.ts
  web/src/testgrid-summary.ts
Labels: lgtm, size/L, approved, cncf-cla: yes
